### ISSUE TITLE
Volume assigning step has failed due to an unknown error

### ISSUE THREAD

**Issue by niklaskorz** [hetznercloud/csi-driver#6] opened 2019-01-14 12:44 UTC
Kubernetes version: 1.13.1
Ubuntu version: 18.04
One master node, two worker nodes (all CX21)
Using the provided example in the README

The volume gets created as I can see it in the Hetzner Cloud dashboard, but it isn't attached to a server.

```yaml
Name:               my-csi-app
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               worker2
Start Time:         Mon, 14 Jan 2019 13:39:28 +0100
Labels:             <none>
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"my-csi-app","namespace":"default"},"spec":{"containers":[{"command":[...
Status:             Pending
IP:
Containers:
  my-frontend:
    Container ID:
    Image:         busybox
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      1000000
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from my-csi-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9pq7v (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  my-csi-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc
    ReadOnly:   false
  default-token-9pq7v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9pq7v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Warning  FailedScheduling    104s (x4 over 110s)  default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled           104s                 default-scheduler        Successfully assigned default/my-csi-app to worker2
  Warning  FailedAttachVolume  37s (x8 over 101s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-6b5bd076-17f9-11e9-a20a-9600001463bf" : rpc error: code = Internal desc = failed to publish volume: Volume assigning step has failed due to an unknown error. (unknown_error)
```

**Comment by thcyron** [comment] 2019-01-15 13:52
Was this a one-time error or does it happen for every volume created?

Does attaching the volume to the server works via Cloud Console? (You should detach immediately afterwards.)

**Comment by niklaskorz** [comment] 2019-01-15 14:41
Mounting over Cloud Console tells me that the server has been created before automatic mounting has been available, which is true because the cluster is older than the cloud volumes feature. I'll see if following the instructions at https://wiki.hetzner.de/index.php/CloudServer/en#volume_automount works and report back.

**Comment by niklaskorz** [comment] 2019-01-15 14:55
Following the instructions and doing a power reset of the servers afterwards did it! It might be worth adding this as hint to README, but otherwise this issue is resolved for me.

**Comment by thcyron** [comment] 2019-01-17 11:35
I had a look at your failed attach API call and it turned out it wasn’t a problem related to automount. It was another problem which was fixed by you rebooting your server.

**Closed by thcyron** 2019-01-17 11:35 UTC

**Comment by Goodsmileduck** [comment] 2019-04-18 10:27
can you share what was a issue, and which servers need to reboot? master?

**Comment by iosifnicolae2** [comment] 2020-11-23 21:44
I've got this error because I was trying to mount more than 16 volumes to the same node.
https://docs.hetzner.com/cloud/volumes/faq/#is-there-a-limit-on-the-number-of-attached-volumes

**Comment by toabi** [comment] 2021-03-17 08:26
I am getting this more and more often. It's especially easy to trigger if you have a stateful-set with 4+ members and `podManagementPolicy = "Parallel"`.

Is there any way to find out what's causing this? Because it easily breaks deployments.

**Comment by InsOpDe** [comment] 2021-04-10 14:19
Rebooting seems to be the only solution for me, too

**Comment by shyblower** [comment] 2021-04-14 15:10
I'm also getting this error, usually shutting the affected cloud server down and booting it up again solved the problem, but at the moment I'm not able to connect more than 10 volumes at the same time. When I try to connect the 11th volume the cloud console says that it is bound, but its device node will not appear in /dev/disk/by-id/.

**Comment by iosifnicolae2** [comment] 2021-04-14 15:21
> I'm also getting this error, usually shutting the affected cloud server down and booting it up again solved the problem, but at the moment I'm not able to connect more than 10 volumes at the same time. When I try to connect the 11th volume the cloud console says that it is bound, but its device node will not appear in /dev/disk/by-id/.


What's hcloud-csi-driver version you are using?

In v.1.5.3 I experienced a lot of issues so I downgraded to v1.5.1.

**Comment by shyblower** [comment] 2021-04-14 15:38
> What hcloud-csi-driver version are you using?
I upgraded to 1.5.3 a few weeks ago which actually seemed to work better, but I don't think it's the csi driver because it also does not work when I try to connect the volumes using the cloud console web gui.

**Comment by iosifnicolae2** [comment] 2021-04-14 15:47
> > What hcloud-csi-driver version are you using?
> 
> I upgraded to 1.5.3 a few weeks ago which actually seemed to work better, but I don't think it's the csi driver because it also does not work when I try to connect the volumes using the cloud console web gui.

Got it.

I've experienced also this problem and I didn't managed to find the root cause. I think that I've solved it temporarly by disconnecting all the volumes from the server using the cloud console web gui, then I've ran `shutdown now` on server and start it again from console.

**Comment by ThomasSteinbach** [comment] 2022-03-02 23:33
Reboot also worked for me. Not very nice.

hcloud-csi-driver 1.6.0

**Comment by ThomasSteinbach** [comment] 2022-03-03 00:15
Following helped me:

1. detaching all volumes
2. server reboot
3. re-attaching all volumes

hcloud-csi-driver 1.6.0

**Comment by djboris9** [comment] 2022-03-03 08:46
I had contact with the Hetzner support regarding this on 16.12.2021, they answered me (in german) that the only way to resolve this problem is to reboot the server:

>  Leider kann das Problem zurzeit nur durch das Stoppen und Starten der Instanz geloest werden. Wir arbeiten bereits an einer Loesung, koennen aber noch nicht sagen wann das Problem behoben sein wird.

**Comment by shyblower** [comment] 2022-03-03 09:11
It gets worse the more volumes you connect to your node ... haven't had it for some time now, though ... probably because atm I don't use that many volumes in parallel.

**Comment by ThomasSteinbach** [comment] 2022-03-04 01:17
@djboris9 Got the same answer from Hetzner. But sometimes just rebooting isn't enough. Then detaching/re-attaching of volumes in the web gui is required.

@shyblower can confirm this. In the documentation is written, that you can attach up to 16 volumes to a server. However it feels like you just could attach 16 **times** a volume to a server. The more volumes you have and the more volumes you create/destroy by the hcloud-csi-driver, the more likely you ran into this problem.

**Comment by tkreuder** [comment] 2022-09-16 04:36
I have the same issue. Is there a new solution to it already, except for the manual approach, like https://github.com/hetznercloud/csi-driver/issues/6#issuecomment-1057530074 ? I am using `hcloud-csi-driver 1.6.0`.
