### ISSUE TITLE
CreateContainerConfigError: Error: secret "hcloud-csi" not found

### ISSUE THREAD

**Issue by niklaspm** [hetznercloud/csi-driver#299] opened 2022-07-04 18:58 UTC
Applying the steps described in "Getting Started" results in the following result (CreateContainerConfigError):
```Warning  Failed     9m11s (x5 over 10m)  kubelet            Error: secret "hcloud-csi" not found```

After changing `meta.name` from `hcloud` as described in "Getting Started (Creating Secret)" to `hcloud-csi` everything works out well.

Is this expected behaviour?

**Comment by 4ND3R50N** [comment] 2022-07-05 07:28
Yeah, this is kind of confusing at the moment.

We are about to release a new csi-driver version. Currently, the master needs a token called `hcloud` while v1.6.0 still needs `hcloud-csi`.

I´ll make this transparent as this is causing confusion!

**Comment by LKaemmerling** [comment] 2022-08-10 07:32
Duplicate of https://github.com/hetznercloud/csi-driver/issues/307

**Closed by LKaemmerling** 2022-08-10 07:32 UTC
