### ISSUE TITLE
Cannot mount volume, not formatted yet?

### ISSUE THREAD

**Issue by markmaas** [hetznercloud/csi-driver#150] opened 2020-10-05 19:26 UTC
Hi All,

I followed the example but the pod never starts, the describe shows:

```
Warning  FailedMount             24s (x6 over 41s)  kubelet, worker-01       MountVolume.MountDevice failed for volume "pvc-58df7562-9f9c-4b4e-a042-df374b9fcd55" : rpc error: code = Internal desc = failed to stage volume: failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/by-id/scsi-0HC_Volume_7394315 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-58df7562-9f9c-4b4e-a042-df374b9fcd55/globalmount
Output: mount: mounting /dev/disk/by-id/scsi-0HC_Volume_7394315 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-58df7562-9f9c-4b4e-a042-df374b9fcd55/globalmount failed: Resource busy
```

It is created though in can see it in the web console and: 
```
Name:          csi-pvc
Namespace:     example
StorageClass:  hcloud-volumes
Status:        Bound
Volume:        pvc-58df7562-9f9c-4b4e-a042-df374b9fcd55
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.hetzner.cloud
               volume.kubernetes.io/selected-node: worker-01
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    my-csi-app
Events:
  Type    Reason                 Age                    From                                                                            Message
  ----    ------                 ----                   ----                                                                            -------
  Normal  WaitForFirstConsumer   2m37s                  persistentvolume-controller                                                     waiting for first consumer to be created before binding
  Normal  ExternalProvisioning   2m37s (x2 over 2m37s)  persistentvolume-controller                                                     waiting for a volume to be created, either by external provisioner "csi.hetzner.cloud" or manually created by system administrator
  Normal  Provisioning           2m37s                  csi.hetzner.cloud_hcloud-csi-controller-0_3c686eaf-b551-458c-a97b-4fe7912edc7c  External provisioner is provisioning volume for claim "example/csi-pvc"
  Normal  ProvisioningSucceeded  2m34s                  csi.hetzner.cloud_hcloud-csi-controller-0_3c686eaf-b551-458c-a97b-4fe7912edc7c  Successfully provisioned volume pvc-58df7562-9f9c-4b4e-a042-df374b9fcd55
```

Any idea's what I might be doing wrong?

**Comment by markmaas** [comment] 2020-10-05 19:32
I've also tried this storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: hcloud-volumes-ext4
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
```

But it gave me the same error.

**Comment by LKaemmerling** [comment] 2020-10-06 12:07
Hey @markmaas,

it looks like there is/was already data on the volume. 

I tried to reproduce your case, i used the following deployment files:
https://github.com/LKaemmerling/hcloud-k8s-test-cases/tree/main/csi_driver/issues/150

I also used the master deployment file version of the CSI driver on k8s 1.18.

I can not reproduce your case.

**Comment by markmaas** [comment] 2020-10-06 18:46
Strange I tried the exact files you linked. and get the same result.

I can see the volume being created and deleted in the hetzner console, so I know quite sure I never installed or formatted it in anyway. And still it is coming back with:

```
MountVolume.MountDevice failed for volume "pvc-2231f02d-7bb9-4dfa-84d4-1ab241c6e363" : rpc error: code = Internal desc = failed to stage volume: failed to mount the volume as "ext4", it already contains unknown data, probably partitions. Mount error: mount failed: exit status 255
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/disk/by-id/scsi-0HC_Volume_7409632 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2231f02d-7bb9-4dfa-84d4-1ab241c6e363/globalmount
Output: mount: mounting /dev/disk/by-id/scsi-0HC_Volume_7409632 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2231f02d-7bb9-4dfa-84d4-1ab241c6e363/globalmount failed: Resource busy
```

**Comment by markmaas** [comment] 2020-10-06 18:53
I figured it out.

I also have OpenEBS running on this system. And it wants to take control over all block devices attached to the system. Including the one this CSI setup wants to format.

After removal of OpenEBS, it all started working.

So now I need to figure out how to get these two to play nice with each other ;-)

**Comment by LKaemmerling** [comment] 2020-10-07 05:54
Okay :) Maybe because of the `is-default-class` annotation? 

I will close this issue because it is not an CSI Driver issue.

**Closed by LKaemmerling** 2020-10-07 05:54 UTC

**Comment by markmaas** [comment] 2020-10-07 17:47
For the next person finding this:  You can adjust the openebs filters to exclude hetzners volumes:

* https://docs.openebs.io/docs/next/ugndm.html#Exclude-filters

**Comment by fmendez89** [comment] 2022-07-27 11:19
Hi @echo-devnull I'm facing the same problem. 
Do you remember how did you filter the the hcloud volumes?

**Comment by radimk** [comment] 2023-10-04 19:41
FWIW when OpenEBS is installed using Helm this is the value that can be configured:
```
ndm:
  filters:
    excludeVendors: "CLOUDBYT,OpenEBS,HC"
```
