### ISSUE TITLE
v1.6.0 tag still references secret name 'hcloud-csi' contrary to README.md

### ISSUE THREAD

**Issue by colinwilson** [hetznercloud/csi-driver#294] opened 2022-06-02 16:18 UTC
I see the [readme.md ](https://github.com/hetznercloud/csi-driver/commit/3907c68013d6ed262cf3b002f537b5c067c459b8) instructs creating a token secret named **`hcloud`**.

But the v1.6.0 tag (manifest) still references secret name **`hcloud-csi`**.

**Comment by 4ND3R50N** [comment] 2022-07-05 07:26
Yeah, this is kind of confusing at the moment. 

We are about to release a new version where the secret name is fitting to the csi driver. When this happens i will inform u here & close this issue :-)

**Comment by LKaemmerling** [comment] 2022-08-10 07:32
Duplicate of https://github.com/hetznercloud/csi-driver/issues/307

**Closed as completed by LKaemmerling** 2022-08-10 07:32 UTC
