### ISSUE TITLE
Snapshot support

### ISSUE THREAD

**Issue by malikkirchner** [hetznercloud/csi-driver#140] opened 2020-08-09 08:13 UTC
Hi,

I am very happy about the growing Hetzer support for Kubernets. Great work! We at xelonic use this csi-driver to provision our volumes in production. Snapshot support would be a great time saver for us.
* Use case 1) A volume claim is deleted with retainPolicy: Retain. It would be great to have automatic snapshot creation, that we can spin up a new volume claim from an earlier snapshot. That way the Hetzner volume would still be represented in k8s and would not dangle. 
* Use case 2) Backups for e.g. cluster migration, database "warm ups", ...

**Comment by grigorov** [comment] 2020-08-18 16:14
+1

**Comment by grizzo-fsm** [comment] 2020-09-08 05:24
+1

**Comment by grengojbo** [comment] 2020-09-11 19:21
+1

**Comment by invidian** [comment] 2020-10-12 12:44
not stale please

**Comment by LKaemmerling** [comment] 2020-10-12 13:23
Duplicate of https://github.com/hetznercloud/csi-driver/issues/88

**Closed by LKaemmerling** 2020-10-12 13:23 UTC
Labels: duplicate
